storage:
    dbPath: ../data/db1
    journal: 
        enabled: true
systemLog:
    destination: file
    path: ../data/db1/mongod.log
    logAppend: true
net:
    port: 27001
    bindIp: 127.0.0.1
processManagement:
    fork: true
security:
    keyFile: ./keyfile
replication:
    replSetName: safari
